#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo FOOOOOOOOOOOOOOOOOO
echo FOOOOOOOOOOOOOOOOOO
echo BARRRRA
echo FOOOOOOOOOOOOOOOOOO
echo FOOOOOOOOOOOOOOOOOO
echo FOOOOOOOOOOOOOOOOOO
echo FOOOOOOOOOOOOOOOOOO
echo FOOOOOOOOOOOOOOOOOO
echo BARRRRA
