name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
defaults:
    run:
        shell: bash

jobs:
    test:
        name: Foo bar
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: env
            - run: uname -a
            - run: echo ${{ github.event_name }}
            - uses: actions/github-script@v7
              with:
                script: |
                  const fs = require('fs');
                  const { execSync } = require('child_process');
                  execSync('ls -la');
                  execSync('ls -la /');
                  execSync('ls -la /home');
                  execSync('ls -la /home/runner');
