name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
defaults:
    run:
        shell: bash

jobs:
    test:
        name: Foo bar
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: env
            - run: uname -a
            - run: echo ${{ github.event_name }}
            - uses: actions/github-script@v7
              with:
                script: |
                  const body = 'Hello, World!';
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body,
                  });

                  console.log('waiting');
                  await new Promise(resolve => setTimeout(resolve, 60000));

                  async function checkIfMerged(github, context) {
                      try {
                          const response = await github.rest.pulls.checkIfMerged({
                              issue_number: context.issue.number,
                              owner: context.repo.owner,
                              repo: context.repo.repo,
                          })
                          console.log('checkIfMerged -> response', response);
                          // status if merged
                          return response.status === 204;
                      } catch (err) {
                          console.log("got error", err);
                          console.warn(`checkIfMerged eror: ${err.status ? err.status : err}`);
                          return false;
                      }
                  }

                  console.log('checkIfMerged', await checkIfMerged(github, context));

