name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
defaults:
    run:
        shell: bash

jobs:
    test:
        name: Foo bar
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: env
            - run: uname -a
            - run: echo ${{ github.event_name }}
            - uses: actions/github-script@v7
              with:
                script: |
                  const body = 'Hello, World!';
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body,
                  })

