on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release branch'
        required: true
        default: 'release'
        type: choice
        options:
        - release
      revision:
        description: 'Which git revision to promote as release? Defaults to main.'
        required: false
        type: string

jobs:
  commit-to-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./release.sh ${{ github.event.inputs.revision || 'main' }} ${{ github.event.inputs.releaseBranch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
